version: "3.7"

services:
  fudan-api:
    env_file:
      - .env
    image: ${FUDAN_IMAGE}
    container_name: ${FUDAN_CONTAINER_NAME}
    volumes:
      - $PWD/fudan-api/logs/:${LOGGING_FILE_PATH}
    networks:
      - ${NET_FUDAN}
    ports:
      - ${FUDAN_API_PORT}:${FUDAN_CONTAINER_PORT}
    restart: always
    depends_on:
      - mysql
      - redis

  redis:
    image: ${REDIS_IMAGE}
    container_name: ${REDIS_CONTAINER_NAME}
    networks:
      - ${NET_FUDAN}
    hostname: redis
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - $PWD/redis/conf/redis.conf:/etc/redis/redis.conf:rw
      - $PWD/redis/data:/data:rw
    command:
      redis-server /etc/redis/redis.conf --appendonly yes
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8

  mysql:
    image: ${MYSQL_IMAGE}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - $PWD/mysql/conf:/etc/mysql/conf.d
      - $PWD/mysql/logs:/logs
      - $PWD/mysql/data:/var/lib/mysql
    container_name: ${MYSQL_CONTAINER_NAME}
    networks:
      - ${NET_FUDAN}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    restart: always
    command: --default-authentication-plugin=mysql_native_password


  fudan-front-web:
    image: ${FUDAN_FRONT_WEB_IMAGE}
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/logs:/var/log/nginx
    container_name: fudan-front-web
    networks:
      - ${NET_FUDAN}
    ports:
      - ${FUDAN_FRONT_PORT}:80
    restart: always
    depends_on:
      - fudan-api

  fudan-end-web:
    image: ${FUDAN_END_WEB_IMAGE}
    container_name: fudan-end-web
    networks:
      - ${NET_FUDAN}
    ports:
      - ${FUDAN_END_PORT}:80
    restart: always
    depends_on:
      - fudan-api


networks:
  localnet:
    external:
      name: localnet
