version: '3'

networks:
  localnet:
    external:
      name: localnet
      
services:
 medusa-web:
   image: ${WEB_IMAGE}
   container_name: ${CONTAINER_NAME}
   user: root
   env_file:
     - .env
   ports:
     - ${HTTPS_PORT}:443
     - ${HTTP_PORT}:80
   volumes:
     - /etc/hosts:/etc/hosts
   networks:
     - localnet
   restart: always 



